@startmindmap
* Herramientas CASE
** Definición
*** Software que automatiza y da soporte a las actividades del proceso de desarrollo de software
**[#Bisque] Clasificación
***_ Upper CASE
**** Planificación
****_ Análisis de requisitos
****_ Estrategia de desarrollo
***_ Middle CASE
**** Análisis
****_ Diseño
***_ Lower CASE
**** Diseño detallado
****_ Implementación
****_ Pruebas
*** Integrated CASE
****_ <back:lightgreen><color darkblue>Todas las fases del ciclo de vida
@endmindmap